### ISSUE TITLE
test failure with hashable < 1.3.1.0

### ISSUE THREAD

**Issue by bergmark** [mmark-md/mmark-ext#23]
`cabal test --constraint 'hashable<1.3.1.0'`

```
      1) Text.MMark.Extension.ObfuscateEmail.obfuscateEmail, when URI has the mailto scheme, produces the correct HTML
           expected: "<p><a href=\"javascript:void(0)\" data-email=\"me@example.org\" class=\"foo\">Enable JavaScript to see this email</a></p>\n"
            but got: "<p><a href=\"javascript:void(0)\" class=\"foo\" data-email=\"me@example.org\">Enable JavaScript to see this email</a></p>\n"

      To rerun use: --match "/Text.MMark.Extension.ObfuscateEmail/obfuscateEmail/when URI has the mailto scheme/produces the correct HTML/"
```

I'm not sure what is going on here. https://www.stackage.org/nightly-2021-03-14 uses hashable-1.3.0.0, mmark-ext-0.2.1.3, mmark-0.0.7.2. Did some other dependency get updated to cause this?

**Comment by mrkkrp** [comment]
This needs to be tested with `hashable-1.3.1.0`. That version has changed how things are ordered in Lucid. I don't have direct control over this in any way, it's just the version of `hashable` should be not `1.3.0.0` but `1.3.1.0` for the test to pass.

**Comment by bergmark** [comment]
Hmm but the current version of lucid this worked that nightly... I'll see if it pops up again and temporarily disable mmark-ext tests until we upgrade hashable in that case. No action required from you.
